### ISSUE TITLE
no include file

### ISSUE THREAD

**Issue by Xclaax** [HKPolyU-UAV/qr_mpc#1]
when I change the 18th line in CMakeLists.txt of qr_mpc, I can't find "include" in "acados".And when I catkin_make,the errors always are "couldn't find the h file",such as "60 | #include "acados/ocp_nlp/ocp_nlp_constraints_common.h"

Please help me,I really really need your help.

**Comment by RockyJBL** [comment]
If there is no include folder with acados folder, the reason could be that you didn't correctly install acados. Maybe you should try to install it again by following the instruction step-by-step.
If it still doesn't work, you may try our other repository [here](https://github.com/HKPolyU-UAV/airo_control_interface), which include docker file so that you can skip installation if you know how to use docker.

**Comment by Xclaax** [comment]
Thank you very much for your reply！ I will try reinstalling acados.

**Comment by Xclaax** [comment]
Thank you again for your reply. I reinstalled acados and resolved the issue！
